### ISSUE TITLE
compatibility with ESP8266 core 2.5.2 - add ICACHE_RAM_ATTR

### ISSUE THREAD

**Issue by sanderkob** [mrfaptastic/Easy-IoT-Arduino-CC1101-LORA#3]
For my project I switched from ESP8266 core 2.4.2 to core 2.5.2, for reasons which have to do with WiFi.
Since core 2.5.2 interrupts have to be explicitly declared in the instruction ram. If not done so this will result in a crash, see e.g. https://github.com/esp8266/Arduino/issues/6237

So please add  'ICACHE_RAM_ATTR' to CC1101.h:

/**
 * Global functions for packet and stream interrupts
 */
inline void  ICACHE_RAM_ATTR interupt_streamReceived() {
    streamReceived = true;
}

inline void  ICACHE_RAM_ATTR interupt_packetReceived() {
    packetReceived = true;
}

**Comment by mrfaptastic** [comment]
Thanks for picking this up. Closing.
