### ISSUE TITLE
Feature request: add Arduino IVR boards

### ISSUE THREAD

**Issue by soosp** [mrfaptastic/Easy-IoT-Arduino-CC1101-LORA#4]
Is this possible to use this library with Arduino AVR boards or pure ATmega chips? They consume less power than ESP MCUs, perform better when operate on batteries.

**Comment by mrfaptastic** [comment]
This library can only be used on the ESP32. If you want something for AVR, please use PXMatrix: https://github.com/2dom/PxMatrix

**Comment by soosp** [comment]
Sorry, but I can't find any relations between PXMatrix and CC1101.

**Comment by mrfaptastic** [comment]
Apologies, I didn't read the git repository name before I replied! Theoretically this library should work with Atmel when using the Arduino framework, but it would probably be easier just to use this library: https://github.com/veonik/arduino-cc1101

My library was written so the CC1101 worked on the ESP8266, which seemed to be problematic for some reason.

**Comment by mrfaptastic** [comment]
I have removed any ESP specific code, so version 1.0.3 of this library should work with AVR, but it has been untested.
