### ISSUE TITLE
odd request

### ISSUE THREAD

**Issue by Asteliks** [mrfaptastic/Easy-IoT-Arduino-CC1101-LORA#5]
Hey this might be an odd request but could you try to make something like this https://github.com/sui77/rc-switch but for CC1101 and the 868Mhz spectrum?

This seems to be a better description https://github.com/sui77/rc-switch/wiki

**Comment by mrfaptastic** [comment]
Hello. I am no longer maintaining this project. You are most welcome to fork it and try. However the CC1101 is completely proprietary in its signal, so unless you’re connecting to CC1101 based rc-switches, it won’t work.

**Comment by Asteliks** [comment]
Thanks for the heads up. Well in that case this might be a problem because my gate needs a 868 Mhz radio working in ASK mode. For some reason I'm having real trouble finding the right hardware. Might you have any suggestions?

**Comment by mrfaptastic** [comment]
Can you open up your gate key without breaking it to see what chip it uses? Could provide a clue. However, trying to reverse engineer RF/Phy level stuff is almost impossible without a signal analyser and about a year of free time.

Perhaps a less painful route is to try some cheap chinese 'gate key' duplicators? Who knows if they'll work though.

https://www.aliexpress.com/wholesale?catId=0&initiative_id=AS_20201221021257&SearchText=868mhz+remote+control

**Comment by Asteliks** [comment]
I've got this blue HSM4-868 remote by hormann and basically this is a PIC16F630 with a TH72032.2.

In general what I want to do is control my gate with the ESP32. I want a notification when the gate is opened/closed and I want to open/close it automatically with my phone when getting home.
