### ISSUE TITLE
problem with interupt_packetReceived()

### ISSUE THREAD

**Issue by MakGyv3r** [mrfaptastic/Easy-IoT-Arduino-CC1101-LORA#6]

**Comment by mrfaptastic** [comment]
Hi @MakGyv3r
Thanks for your kind words! I take it you used the version from the git to resolve this? I by coincidence fixed this issue a few days ago. Not sure many people use these CC1101's anymore, at least with ESP32, given nobody raising such an issue on this library in three years! At least it works now :-)

**Comment by MakGyv3r** [comment]
hi @mrfaptastic,

I wasn't sure if you would reply, I will say it again I really appreciative of your work thank you very much. 
Yes, I used this version instead of the version without Lora, and this version works (i think I will add a simple chat with a sleeping mode example between two devices after I will finish building it).
I think CC1101 can be very useful if a bit complex for some projects.
I am building a project with 20 Arduino nano on batteries that will sleep till receiving transmission and ESP32 as a getaway I am not sure if it is possible with CC1101 but I am trying, I was wondering if it is possible to pick your brain on this I am new to all RF communications modules stuff?

**Comment by mrfaptastic** [comment]
Hi @MakGyv3r, well I knew nothing about RF communication modules until I wrote this library and played with a $2 cc1101. 

So long as you use this same library and RF settings (radio.begin(CFREQ_868, KBPS_250, ...etc) on both the recieving and sending sides you'll have no problems... So this library, as the CC1101 configuration at both the sending and recieving modules must match.

> I am building a project with 20 Arduino nano on batteries that will sleep till receiving transmission and ESP32 as a getaway I am not sure if it is possible with CC1101 but I am trying, I was wondering if it is possible to pick your brain on this I am new to all RF communications modules stuff?

Yes, it should be easy.  I can't help you with how to put an Arduino Nano / AVR to sleep and wake up, but somebody has already done that and there would be plenty of tutorials: 
https://github.com/SpaceTeddy/CC1101/blob/master/examples/Arduino/Rx_demo/Rx_demo.ino

My suggestion:
* Install this library on each NANO and the recieving ESP with it's own device ID (or have the ID stored in EEPROM)
* Write the AVR / Nano sleep code.

Then in your sketch:
* In the Nano, call:  radio.setPowerDownState().
* Then the code to put the nano to sleep.
* Then when the Nano is ready to wake up to transmit, call radio.wakeUp()
* Then transmit,
* Repeat.

I've updated the library to remove the ESP-specific code, so you should be able to run it on the Arduino Nano. I've tested that it does compile for AVR... but I can't test that as I don't have a nano etc.  Best of luck

**Comment by mrfaptastic** [comment]
Just tested some code at least on an ESP32 that put the CC1101 to sleep woke it back up and recieved a packet. Seems to work. So you should be all good to go with this library, just need to write your Arduino sleep code.

**Comment by MakGyv3r** [comment]
Hi @mrfaptastic,

wow, thank you for the detailed answer. 

Something I didn't understand, I want to use the option of sending to sleep the ESP32 and putting the CC1101 also in a state of sleep and wake up the CC1101 and after that the esp32 if there is communication in the address and the channel, I didn't find this option in the library, is it possible?  

Also, the line with " // If in RX state and CCA is enabled: Only go to TX if channel is clear" is empty, is there a command for this in the library?

**Comment by mrfaptastic** [comment]
>  I didn't find this option in the library, is it possible?

There's too many configuration permutations the cc1101 could have and this library is only for basic stuff. Sounds like from a cc1101 perspective you're looking at sleep and 'Wake on Radio' (WoR)? 

If so, you will need to customise the library manually. WoR is a cc1101 register config thing that you can change easily in the .cpp and experiment yourself. Googling 'cc1101 AN047'

Cheers.

**Comment by mrfaptastic** [comment]
Personally I think it'd be easier to only put the ESP32 to sleep only given it's the power suck... and hack the isPacketReceived() interrupt handler in the library to wake up the ESP32. 

CC11101 WoR stuff from reading the spec sheet looks like a pain in the arse to get right.

**Comment by MakGyv3r** [comment]
great thank you, I will do that. 

 I hope this will be my last question, if I have the esp32 with the CC1101 connected to the grid and I give it lots of power and a good antenna, can it transmit and receive information to the other devices with lower quality antenna and less power? 
what I want to ask is if I am giving my RF device more power, a better antenna, and maybe an amplifier will it improve the RF communication covrage (transmit and receiving) in theory? 

@mrfaptastic

**Comment by mrfaptastic** [comment]
Your guess is as good as mine. That's RF engineering stuff I know nothing about.

Just because it's connected to grid won't make it any more powerful than those battery powered.

**Comment by MakGyv3r** [comment]
thank you for all the information!

**Comment by mrfaptastic** [comment]
No problems, best of luck with the project - will be interested to see how you go.

I've made some minor improvements to the library as well in the git.

**Comment by MakGyv3r** [comment]
geat I will.
 just something that I encountered while sending messages between the CC1101. is it possible that the max message can be resicve by the CC1101 is 55 bytes? 
do you want to continue speaking throw email?

**Comment by mrfaptastic** [comment]
Raised: https://github.com/mrfaptastic/Easy-IoT-Arduino-CC1101-LORA/issues/7

I'd just keep it at 61 and ignore the null bytes after the 55th byte in the recieved payload.

**Comment by mrfaptastic** [comment]
The max size of any single radio transmission is 64 bytes in the CC1101, but taking into account overheads, 61 is the real max, and this library uses 4 bytes of that 61 for it's own protocol if you use sendBytes or sendChars
